#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Snaleboda.Xamarin.Droid.Resource", IsApplication=true)]

namespace Snaleboda.Xamarin.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_pig = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pig = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int action_call = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int action_contacts = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int action_email = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int action_news = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int action_report = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int description = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int email = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int image = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int info = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int number = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int progressBar = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int send = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int title = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int contact_listitem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int news_listitem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int report = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int contact = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int Large = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Medium = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Small = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Small_Bold = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
